spring:
  application:
    name: zuul-service
    
server:
  port: 8791

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    edge-service:
      path: /edge/**
      serviceId: edge-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@eureka1:8761/eureka,http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@eureka2:8762/eureka
    #registerWithEureka: false
  instance:
    #hostname: localhost
    #hostname: zuul
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
      



